ci: exclude builds that are known to be broken upstream
To reduce noise. Re-enable them when related issues are resolved.

diff --git a/.github/workflows/fate.yml b/.github/workflows/fate.yml
--- a/.github/workflows/fate.yml
+++ b/.github/workflows/fate.yml
@@ -42,17 +42,18 @@ jobs:
             debug: true
             assert: false
             cet: false
-          - os: windows-2025
-            arch: x86_32
-            target_arch: x86
-            host_arch: amd64
-            compiler: msvc
-            asan: true
-            asm: false
-            shared: false
-            debug: false
-            assert: false
-            cet: false
+          # fate-lossless-tak fails on VS2022, enable after VS2026 update
+          # - os: windows-2025
+          #   arch: x86_32
+          #   target_arch: x86
+          #   host_arch: amd64
+          #   compiler: msvc
+          #   asan: true
+          #   asm: false
+          #   shared: false
+          #   debug: false
+          #   assert: false
+          #   cet: false
         exclude:
           - arch: amd64
             os: windows-11-arm
@@ -317,15 +318,17 @@ jobs:
           - sys: "clang64"
             os: "windows-latest"
             arch: amd64
-          - sys: "mingw64"
-            os: "windows-latest"
-            arch: amd64
+          # Enable once https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122793 is fixed
+          # - sys: "mingw64"
+          #   os: "windows-latest"
+          #   arch: amd64
           - sys: "mingw32"
             os: "windows-latest"
             arch: amd64
-          - sys: "ucrt64"
-            os: "windows-latest"
-            arch: amd64
+          # Enable once https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122793 is fixed
+          # - sys: "ucrt64"
+          #   os: "windows-latest"
+          #   arch: amd64
           - sys: "clangarm64"
             os: "windows-11-arm"
             arch: arm64
@@ -572,6 +575,8 @@ jobs:
           - cet: true
           # Enable if needed
           - compiler: icx
+          # Enable after https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/20919 is merged
+          - sde: true
     env:
       CONF: ${{ matrix.arch }}-${{ matrix.compiler }}${{ matrix.asan && '-asan' || '' }}${{ matrix.msan && '-msan' || '' }}${{ matrix.shared && '-shared' || '' }}${{ matrix.cet && '-cet' || '' }}${{ matrix.sde && '-sde' || '' }}${{ matrix.asm && '-asm' || '' }}
       UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
@@ -715,106 +720,108 @@ jobs:
           readelf -n .github/fate/install/bin/ffmpeg
           readelf -r .github/fate/install/bin/ffmpeg
 
-  debian:
-    name: ${{ matrix.arch }}-${{ matrix.compiler }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-24.04, ubuntu-24.04-arm]
-        arch: [amd64, arm64]
-        compiler: [gcc-snapshot]
-        exclude:
-          - arch: amd64
-            os: ubuntu-24.04-arm
-          - arch: arm64
-            os: ubuntu-24.04
-    container:
-      image: debian:unstable-slim
-    env:
-      CONF: ${{ matrix.arch }}-${{ matrix.compiler }}
-      UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
-    steps:
-      - name: Print CPU Info
-        run: |
-          cat /proc/cpuinfo
-      - name: Install dependencies
-        run: |
-          apt-get update
-          apt-get install -y ${{ matrix.compiler }} git libsdl2-dev libvulkan-dev glslang-dev spirv-tools libxml2-utils make mold nasm openssh-client pkgconf rsync zlib1g-dev
-      - uses: actions/checkout@v6
-      - name: Checkout FFmpeg
-        uses: actions/checkout@v6
-        with:
-          fetch-depth: 0 # For fate version string
-          repository: ffmpeg/ffmpeg
-          path: .github/fate/src
-      - name: Restore Cached FATE Samples
-        id: cache
-        uses: actions/cache/restore@v4
-        with:
-          path: .github/fate/samples
-          key: fate-samples-dummy
-          restore-keys: fate-samples-
-      - name: Sync FATE Samples
-        id: samples
-        run: |
-          mkdir -p .github/fate/samples
-          rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
-          echo "hash=$(find .github/fate/samples -type f -printf "%P %s %T@\n" | sort | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
-      - name: Cache FATE Samples
-        if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
-        uses: actions/cache/save@v4
-        with:
-          path: .github/fate/samples
-          key: fate-samples-${{ steps.samples.outputs.hash }}
-      - name: Set up SSH
-        env:
-          HOST: fate.ffmpeg.org
-          FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
-        run: |
-          export HOME="/root"
-          mkdir -p "$HOME/.ssh"
-          chmod 700 "$HOME/.ssh"
-          ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
-          chmod 644 "$HOME/.ssh/known_hosts"
-          SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
-          if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
-            echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
-            exit 1
-          fi
-          echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
-          chmod 600 "$HOME/.ssh/id_ed25519"
-      - name: Build
-        id: build
-        run: |
-          export PATH="/usr/lib/gcc-snapshot/bin:${PATH}"
-          export LD_RUN_PATH="/usr/lib/gcc-snapshot/lib"
-          gcc --version
-          cd .github/fate/src
-          ./tests/fate.sh ../${{ env.CONF }}
-      - name: Print version
-        if: always()
-        run: |
-          cat .github/fate/version-${{ env.CONF }}
-      - name: Print configure.log
-        if: always()
-        run: |
-          cat .github/fate/configure.log
-      - name: Print config.log
-        if: always()
-        run: |
-          cat .github/fate/build/ffbuild/config.log
-      - name: Print compile.log
-        if: always()
-        run: |
-          cat .github/fate/compile.log
-      - name: Print test.log
-        if: always()
-        run: |
-          cat .github/fate/test.log
-      - name: readelf
-        run: |
-          readelf -S .github/fate/install/bin/ffmpeg
-          readelf -n .github/fate/install/bin/ffmpeg
-          readelf -r .github/fate/install/bin/ffmpeg
+  # gcc 16 (20251111-1) is broken, enable after new one is released, upstream bug is fixed
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=122797
+  # debian:
+  #   name: ${{ matrix.arch }}-${{ matrix.compiler }}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-24.04, ubuntu-24.04-arm]
+  #       arch: [amd64, arm64]
+  #       compiler: [gcc-snapshot]
+  #       exclude:
+  #         - arch: amd64
+  #           os: ubuntu-24.04-arm
+  #         - arch: arm64
+  #           os: ubuntu-24.04
+  #   container:
+  #     image: debian:unstable-slim
+  #   env:
+  #     CONF: ${{ matrix.arch }}-${{ matrix.compiler }}
+  #     UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1
+  #   steps:
+  #     - name: Print CPU Info
+  #       run: |
+  #         cat /proc/cpuinfo
+  #     - name: Install dependencies
+  #       run: |
+  #         apt-get update
+  #         apt-get install -y ${{ matrix.compiler }} git libsdl2-dev libvulkan-dev glslang-dev spirv-tools libxml2-utils make mold nasm openssh-client pkgconf rsync zlib1g-dev
+  #     - uses: actions/checkout@v6
+  #     - name: Checkout FFmpeg
+  #       uses: actions/checkout@v6
+  #       with:
+  #         fetch-depth: 0 # For fate version string
+  #         repository: ffmpeg/ffmpeg
+  #         path: .github/fate/src
+  #     - name: Restore Cached FATE Samples
+  #       id: cache
+  #       uses: actions/cache/restore@v4
+  #       with:
+  #         path: .github/fate/samples
+  #         key: fate-samples-dummy
+  #         restore-keys: fate-samples-
+  #     - name: Sync FATE Samples
+  #       id: samples
+  #       run: |
+  #         mkdir -p .github/fate/samples
+  #         rsync -vrltLW --timeout=60 rsync://fate-suite.ffmpeg.org/fate-suite/ .github/fate/samples/
+  #         echo "hash=$(find .github/fate/samples -type f -printf "%P %s %T@\n" | sort | sha256sum | cut -d' ' -f1)" >> $GITHUB_OUTPUT
+  #     - name: Cache FATE Samples
+  #       if: ${{ format('fate-samples-{0}', steps.samples.outputs.hash) != steps.cache.outputs.cache-matched-key }}
+  #       uses: actions/cache/save@v4
+  #       with:
+  #         path: .github/fate/samples
+  #         key: fate-samples-${{ steps.samples.outputs.hash }}
+  #     - name: Set up SSH
+  #       env:
+  #         HOST: fate.ffmpeg.org
+  #         FINGERPRINT: "76:9f:68:32:04:1e:d5:d4:ec:47:3f:dc:fc:18:17:86"
+  #       run: |
+  #         export HOME="/root"
+  #         mkdir -p "$HOME/.ssh"
+  #         chmod 700 "$HOME/.ssh"
+  #         ssh-keyscan -t ecdsa "$HOST" > "$HOME/.ssh/known_hosts"
+  #         chmod 644 "$HOME/.ssh/known_hosts"
+  #         SERVER_FINGERPRINT="$(ssh-keygen -E md5 -lf "$HOME/.ssh/known_hosts" | grep "$HOST" | awk '{gsub(/^MD5:/, "", $2); print $2}')"
+  #         if [ "$SERVER_FINGERPRINT" != "$FINGERPRINT" ]; then
+  #           echo "Fingerprint $SERVER_FINGERPRINT does not match expected $FINGERPRINT"
+  #           exit 1
+  #         fi
+  #         echo "${{ secrets.FATE_SSH_KEY }}" > "$HOME/.ssh/id_ed25519"
+  #         chmod 600 "$HOME/.ssh/id_ed25519"
+  #     - name: Build
+  #       id: build
+  #       run: |
+  #         export PATH="/usr/lib/gcc-snapshot/bin:${PATH}"
+  #         export LD_RUN_PATH="/usr/lib/gcc-snapshot/lib"
+  #         gcc --version
+  #         cd .github/fate/src
+  #         ./tests/fate.sh ../${{ env.CONF }}
+  #     - name: Print version
+  #       if: always()
+  #       run: |
+  #         cat .github/fate/version-${{ env.CONF }}
+  #     - name: Print configure.log
+  #       if: always()
+  #       run: |
+  #         cat .github/fate/configure.log
+  #     - name: Print config.log
+  #       if: always()
+  #       run: |
+  #         cat .github/fate/build/ffbuild/config.log
+  #     - name: Print compile.log
+  #       if: always()
+  #       run: |
+  #         cat .github/fate/compile.log
+  #     - name: Print test.log
+  #       if: always()
+  #       run: |
+  #         cat .github/fate/test.log
+  #     - name: readelf
+  #       run: |
+  #         readelf -S .github/fate/install/bin/ffmpeg
+  #         readelf -n .github/fate/install/bin/ffmpeg
+  #         readelf -r .github/fate/install/bin/ffmpeg
